### ISSUE TITLE
cursor moves forward in collect block

### ISSUE THREAD

**Issue by irgaly** [JuulLabs/indexeddb#75]
Thank you for this very cool library. I'm using this library in my Kotlin Multiplatform project (https://github.com/irgaly/kottage/pull/58).

It seems a cursor in collect block moves forward before completing the block.

I make a reproducer on my fork repository: https://github.com/irgaly/indexeddb/pull/1

---

steps to reproduce:

* get a cursor Flow by openCursor()
* collect cursor with block:
    * call two or more suspend functions in collect block. (that functions are indexeddb's transaction operations.)
    * -> now, cursor has moved forward

expected behavior:

* cursor stays current position until collect block completes.

## Code

https://github.com/irgaly/indexeddb/blob/57f30479f8c8f82577718127f0e9c178135410b8/reproducer/src/jsMain/kotlin/reproducer/Main.kt

```kotlin
fun main() {
    window.onload = {
        MainScope().launch {
            val database = openDatabase("test", 1) { database, old, new ->
                if (old < 1) {
                    database.createObjectStore("store", KeyPath("id"))
                }
            }
            database.writeTransaction("store") {
                val store = objectStore("store")
                store.clear()
                store.add(jso<Data> { id = 0; name = "a" })
                store.add(jso<Data> { id = 1; name = "b" })
                store.add(jso<Data> { id = 2; name = "c" })
                store.add(jso<Data> { id = 3; name = "d" })
                store.add(jso<Data> { id = 4; name = "e" })
                store.add(jso<Data> { id = 5; name = "f" })
                store.add(jso<Data> { id = 6; name = "g" })
                store.add(jso<Data> { id = 7; name = "h" })
                store.add(jso<Data> { id = 8; name = "i" })
                store.add(jso<Data> { id = 9; name = "j" })
            }
            database.writeTransaction("store") {
                val store = objectStore("store")
                store.openCursor()
                    .collect { cursor ->
                        console.log("1: cursor.value = ${JSON.stringify(cursor.value, null, "  ")}")
                        console.log("2: store.get()")
                        store.get(Key("other"))
                        console.log("3: cursor.value = ${JSON.stringify(cursor.value, null, "  ")}")
                        console.log("4: store.get()")
                        store.get(Key("other"))
                        console.log("5: cursor.value = ${JSON.stringify(cursor.value, null, "  ")}")
                        console.log("6: store.get()")
                        store.get(Key("other"))
                        console.log("7: cursor.value = ${JSON.stringify(cursor.value, null, "  ")}")
                        console.log("8: delete()")
                        cursor.delete()
                        console.log("9: cursor.value = ${JSON.stringify(cursor.value, null, "  ")}")
                    }
            }
        }
    }
}

fun <T : Any> jso(): T = js("({})") as T
inline fun <T : Any> jso(block: T.() -> Unit): T = jso<T>().apply(block)

external interface Data {
    var id: Int
    var name: String
}
```

## Output

environment: 
M1, macOS 12.6, Chrome 107.0.5304.87

console log:

```
1: cursor.value = {
  "id": 0,
  "name": "a"
}
2: store.get()
3: cursor.value = {
  "id": 0,
  "name": "a"
}
4: store.get()
5: cursor.value = {
  "id": 1,
  "name": "b"
}
6: store.get()
7: cursor.value = {
  "id": 2,
  "name": "c"
}
8: delete()
DOMException: Failed to execute 'delete' on 'IDBCursor': The cursor is being iterated or has iterated past its end.
    at WriteTransaction.delete_t3salm_k$ (webpack-internal:///./kotlin/indexeddb-core.js:1097:48)
    at main$lambda$slambda$slambda$slambda.doResume_5yljmg_k$ (webpack-internal:///./kotlin/indexeddb-reproducer.js:127:59)
    at CoroutineImpl.resumeWith_7onugl_k$ (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:16089:33)
    at CoroutineImpl.resumeWith_s3a3yh_k$ (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:16135:17)
    at resume (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:9405:50)
    at resumeUnconfined (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:9362:9)
    at dispatch (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:9312:9)
    at dispatchResume (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:955:5)
    at resumeImpl (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:1011:11)
    at resumeImpl$default (webpack-internal:///./kotlin/kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js:1037:12)
```

![image](https://user-images.githubusercontent.com/1311446/198884099-074f2110-d9d4-4f82-bfcc-65d4615eeb3a.png)

**Comment by cedrickcooke** [comment]
Thanks for the clear repro steps, I'll take a look at this as soon as I have some free cycles.
